"""Regenerate results/REPORT.md — every number quoted in the README comes from here.

    python report.py
"""
from __future__ import annotations

import os

import numpy as np
import pandas as pd

from amd_engine import Params
from backtest import UNIVERSE, backtest
from data import is_cached, klines

HERE = os.path.dirname(__file__)
OUT = os.path.join(HERE, "results")
TIMEFRAMES = [("1h", 730), ("4h", 1460), ("15m", 365)]


def agg(r: pd.Series) -> dict:
    r = r.to_numpy()
    if len(r) == 0:
        return {"trades": 0, "win %": np.nan, "avg R": np.nan, "total R": 0.0, "PF": np.nan, "max DD R": 0.0}
    eq = np.cumsum(r)
    dd = (np.maximum.accumulate(np.concatenate([[0], eq]))[1:] - eq).max()
    loss = -r[r < 0].sum()
    return {"trades": len(r), "win %": (r > 0).mean() * 100, "avg R": r.mean(), "total R": r.sum(),
            "PF": r[r > 0].sum() / loss if loss > 0 else np.inf, "max DD R": dd}


def table(rows: dict[str, dict]) -> str:
    """Markdown table from {row label: {column: value}} (no extra dependencies)."""
    cols = list(next(iter(rows.values())).keys())

    def fmt(v):
        if isinstance(v, (int, np.integer)):
            return str(v)
        if v is None or (isinstance(v, float) and np.isnan(v)):
            return "–"
        return "∞" if np.isinf(v) else f"{v:.2f}"
    out = ["| | " + " | ".join(cols) + " |", "|---" * (len(cols) + 1) + "|"]
    out += [f"| {k} | " + " | ".join(fmt(r[c]) for c in cols) + " |" for k, r in rows.items()]
    return "\n".join(out)


def btc_context(trades: pd.DataFrame, tf_hours: float) -> pd.Series:
    """BTC 4h EMA21/55 trend at signal time, relative to the trade: with / flat / against."""
    b = klines("BTCUSDT", "4h", 1460)
    c = b["close"]
    ef, es = c.ewm(span=21, adjust=False).mean(), c.ewm(span=55, adjust=False).mean()
    trend = np.where((c > es) & (ef > es), 1, np.where((c < es) & (ef < es), -1, 0))
    ctx = pd.DataFrame({"t": b["time"] + pd.Timedelta(hours=4), "btc": trend}).sort_values("t")
    t = trades.copy()
    t["sig_time"] = t["entry_time"] + pd.Timedelta(hours=tf_hours)
    t = pd.merge_asof(t.sort_values("sig_time"), ctx, left_on="sig_time", right_on="t", direction="backward")
    rel = np.select([t["btc"] == t["direction"], t["btc"] == 0], ["with BTC", "BTC flat"], "against BTC")
    return pd.Series(rel, index=t.index), t


def main():
    os.makedirs(OUT, exist_ok=True)
    p = Params()
    lines = ["# AMD × Volume Profile — backtest report", "",
             "Generated by `research/report.py` on Binance spot data (closed bars only).",
             f"Universe: {', '.join(s[:-4] for s in UNIVERSE)}.",
             f"Costs: {p.fee_pct}% fee + {p.slip_pct}% slippage per side, charged in R. "
             "Results are in R (multiples of the amount risked per trade).", "",
             "Default parameters: " + ", ".join(f"`{k}={v}`" for k, v in vars(p).items()
                                                if k not in ("fee_pct", "slip_pct")), ""]
    for tf, days in TIMEFRAMES:
        # 1h/4h always run on the full universe; slower-to-download timeframes use what's cached
        syms = UNIVERSE if tf in ("1h", "4h") else [s for s in UNIVERSE if is_cached(s, tf, days)]
        if not syms:
            continue
        try:
            per, trades = backtest(syms, tf, days, p)
        except Exception as e:   # e.g. data not downloaded
            lines += [f"## {tf}", "", f"_skipped: {e}_", ""]
            continue
        if trades.empty:
            continue
        trades["entry_time"] = pd.to_datetime(trades["entry_time"], utc=True)
        trades = trades.sort_values("entry_time").reset_index(drop=True)
        trades.to_csv(os.path.join(OUT, f"trades_{tf}.csv"), index=False)
        start, end = trades["entry_time"].min().date(), trades["entry_time"].max().date()
        lines += [f"## {tf} — last {days} days ({start} → {end})", ""]
        if len(syms) < len(UNIVERSE):
            lines += [f"_Only {len(syms)} coins: {', '.join(s[:-4] for s in syms)}._", ""]
        lines += [table({"All trades": agg(trades["r_net"])}), ""]

        half = trades["entry_time"].quantile(0.5)
        lines += ["**First half vs second half of the trades.** On 1h the defaults were chosen as the settings that "
                  "did best in the *weaker* of the two halves, so neither half is untouched; 4h and 15m were never tuned.", "",
                  table({"First half": agg(trades.loc[trades.entry_time < half, "r_net"]),
                         "Second half": agg(trades.loc[trades.entry_time >= half, "r_net"])}), ""]

        side = np.where(trades["direction"] == 1, "Long", "Short")
        lines += ["**By side:**", "", table({s: agg(trades.loc[side == s, "r_net"]) for s in ("Long", "Short")}), ""]

        tf_h = {"15m": 0.25, "1h": 1, "4h": 4}[tf]
        rel, tt = btc_context(trades, tf_h)
        rows = {}
        for sd, dv in (("Long", 1), ("Short", -1)):
            for k in ("with BTC", "BTC flat", "against BTC"):
                rows[f"{sd} · {k}"] = agg(tt.loc[(tt.direction == dv) & (rel == k), "r_net"])
        filt = tt[(tt.direction == 1) | (rel != "against BTC")]
        rows["**Shorts filtered (default)**"] = agg(filt["r_net"])
        lines += ["**Market context** (BTC 4h EMA 21/55 trend as a stand-in for the script's TOTAL/USDT.D grade):",
                  "", table(rows), ""]

        hour = trades["entry_time"].dt.hour
        sess = pd.cut(hour, [-1, 7, 12, 16, 23], labels=["Asia 00–08 UTC", "London 08–13 UTC",
                                                        "London/NY 13–17 UTC", "NY late 17–24 UTC"])
        lines += ["**By session (entry hour, UTC):**", "",
                  table({str(s): agg(trades.loc[sess == s, "r_net"]) for s in sess.cat.categories}), ""]
        wk = trades["entry_time"].dt.dayofweek >= 5
        lines += ["**Weekdays vs weekends:**", "",
                  table({"Mon–Fri": agg(trades.loc[~wk, "r_net"]), "Sat–Sun": agg(trades.loc[wk, "r_net"])}), ""]

        coin = {s[:-4]: agg(trades.loc[trades.symbol == s, "r_net"]) for s in syms}
        lines += ["**Per coin:**", "", table(coin), ""]

    with open(os.path.join(OUT, "REPORT.md"), "w") as f:
        f.write("\n".join(lines))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
