"""Generate the strategy script from the indicator so both share one engine.

    python tools/build_strategy.py
The indicator is the source of truth; never edit the generated strategy by hand.
"""
import os
import re

ROOT = os.path.join(os.path.dirname(__file__), "..", "pine")
SRC = os.path.join(ROOT, "AMD_Volume_Profile_Crypto.pine")
DST = os.path.join(ROOT, "AMD_Volume_Profile_Crypto_Strategy.pine")

HEADER = ('strategy("AMD × Volume Profile — Crypto [Strategy]", shorttitle = "AMD-VP Strategy", overlay = true, '
          'max_bars_back = 1000, max_boxes_count = 500, max_lines_count = 500, max_labels_count = 500, '
          'initial_capital = 10000, currency = currency.USD, default_qty_type = strategy.fixed, default_qty_value = 1, '
          'commission_type = strategy.commission.percent, commission_value = 0.05, slippage = 2, '
          'process_orders_on_close = true, pyramiding = 0, margin_long = 10, margin_short = 10)\n\n'
          'G_STR = "⓪ Strategy"\n'
          'float riskPct = input.float(1.0, "Risk per trade (% of equity)", minval = 0.1, maxval = 10, step = 0.1, '
          'group = G_STR, tooltip = "Position size = equity × risk % ÷ stop distance. Margin is set to 10 % (10× max leverage).")')

ORDERS = '''// ═══ Strategy orders (generated by tools/build_strategy.py) ══════════════════════════
// Confirmation entries fill at the signal bar's close (process_orders_on_close), exactly
// like the engine. Stops/targets are broker orders from the next bar; any exit the engine
// takes (incl. "accepted back in value") also flattens the position.
if evEntry and entryMode == "Confirmation"
    strategy.entry("AMD", barDir == 1 ? strategy.long : strategy.short, qty = strategy.equity * riskPct / 100.0 / tRisk, comment = (barDir == 1 ? "L " : "S ") + tGrade)
if state == S_IN_TRADE and evExit == 0
    strategy.exit("AMD x", from_entry = "AMD", stop = tStop, limit = tTarget, comment_loss = "stop", comment_profit = "target")
if evExit != 0
    strategy.close("AMD", comment = evExit == X_ACCEPT ? "back in value" : "exit")
if entryMode == "Limit"
    if state == S_DISPLACED and not doReset and bar_index + 1 - dispBar <= maxPullbackBars
        float limP = entryLvl + barDir * touchTolAtr * atrS
        [sL, rL, okL] = f_risk(limP, deepLvl - barDir * stopBufferAtr * atrS, barDir, atrS)
        if okL and f_ctxPass(barDir) and timeOk
            strategy.entry("AMD", barDir == 1 ? strategy.long : strategy.short, qty = strategy.equity * riskPct / 100.0 / rL, limit = limP, comment = "limit")
            strategy.exit("AMD x", from_entry = "AMD", stop = sL, limit = limP + barDir * tpR * rL, comment_loss = "stop", comment_profit = "target")
        else
            strategy.cancel("AMD")
    else if strategy.position_size == 0
        strategy.cancel("AMD")
'''


def build():
    src = open(SRC, encoding="utf-8").read()
    out, n = re.subn(r'^indicator\(.*\)$', HEADER, src, count=1, flags=re.M)
    assert n == 1, "indicator() declaration not found"
    assert "// @@STRATEGY_ORDERS@@" in out
    out = out.replace("// @@STRATEGY_ORDERS@@", ORDERS.rstrip())
    out = re.sub(r'^alertcondition\(.*\)\n', "", out, flags=re.M)   # indicator-only
    banner = ("// ⚠ GENERATED FILE — edit AMD_Volume_Profile_Crypto.pine and run tools/build_strategy.py\n")
    out = out.replace("//@version=6\n", "//@version=6\n" + banner, 1)
    with open(DST, "w", encoding="utf-8") as f:
        f.write(out)
    print("wrote", os.path.relpath(DST))


if __name__ == "__main__":
    build()
